export const DISPATCH_TASK_REQUESTED = 'DISPATCH_TASK_REQUESTED';
export const DISPATCH_TASK_SUCCEEDED = 'DISPATCH_TASK_SUCCEEDED';
export const DISPATCH_TASK_FAILED = 'DISPATCH_TASK_FAILED';

// APP
export const APP_SET_DETECTION_STATE = 'APP_SET_DETECTION_STATE';

// VISUAL
export const VISUAL_RESET = 'VISUAL_RESET';
export const VISUAL_SET_BACKGROUND_FILE = 'VISUAL_SET_BACKGROUND_FILE';
export const VISUAL_SET_TEXT = 'VISUAL_SET_TEXT';

// SPEECH
export const SPEECH_TEXT_REQUESTED = 'SPEECH_TEXT_REQUESTED';
export const SPEECH_TEXT_SUCCEEDED = 'SPEECH_TEXT_SUCCEEDED';
export const SPEECH_TEXT_FAILED = 'SPEECH_TEXT_FAILED';

export const SPEECH_RATE_REQUESTED = 'SPEECH_RATE_REQUESTED';
export const SPEECH_RATE_SUCCEEDED = 'SPEECH_RATE_SUCCEEDED';
export const SPEECH_RATE_FAILED = 'SPEECH_RATE_FAILED';

export const SPEECH_PITCH_REQUESTED = 'SPEECH_PITCH_REQUESTED';
export const SPEECH_PITCH_SUCCEEDED = 'SPEECH_PITCH_SUCCEEDED';
export const SPEECH_PITCH_FAILED = 'SPEECH_PITCH_FAILED';

export const SPEECH_LOCALE_REQUESTED = 'SPEECH_LOCALE_REQUESTED';
export const SPEECH_LOCALE_SUCCEEDED = 'SPEECH_LOCALE_SUCCEEDED';
export const SPEECH_LOCALE_FAILED = 'SPEECH_LOCALE_FAILED';
