export const DISPATCH_TASK_REQUESTED = 'DISPATCH_TASK_REQUESTED';
export const DISPATCH_TASK_SUCCEEDED = 'DISPATCH_TASK_SUCCEEDED';
export const DISPATCH_TASK_FAILED = 'DISPATCH_TASK_FAILED';

// APP
export const APP_SET_DETECTION_STATE = 'APP_SET_DETECTION_STATE';

// VISUAL
export const VISUAL_RESET = 'VISUAL_RESET';
export const VISUAL_SET_BACKGROUND_FILE = 'VISUAL_SET_BACKGROUND_FILE';
export const VISUAL_SET_TEXT = 'VISUAL_SET_TEXT';

// SPEECH
export const SPEECH_SAY_TEXT_REQUESTED = 'SPEECH_SAY_TEXT_REQUESTED';
export const SPEECH_SAY_TEXT_STATUS = 'SPEECH_SAY_TEXT_STATUS';

export const SPEECH_SET_RATE_REQUESTED = 'SPEECH_SET_RATE_REQUESTED';
export const SPEECH_SET_RATE_STATUS = 'SPEECH_SET_RATE_STATUS';

export const SPEECH_SET_PITCH_REQUESTED = 'SPEECH_SET_PITCH_REQUESTED';
export const SPEECH_SET_PITCH_STATUS = 'SPEECH_SET_PITCH_STATUS';

export const SPEECH_SET_LOCALE_REQUESTED = 'SPEECH_SET_LOCALE_REQUESTED';
export const SPEECH_SET_LOCALE_STATUS = 'SPEECH_SET_LOCALE_STATUS';
