export const DISPATCH_TASK_REQUESTED = 'DISPATCH_TASK_REQUESTED';
export const DISPATCH_TASK_SUCCEEDED = 'DISPATCH_TASK_SUCCEEDED';
export const DISPATCH_TASK_FAILED = 'DISPATCH_TASK_FAILED';

// APP
export const APP_SET_DETECTION_STATE = 'APP_SET_DETECTION_STATE';

export const APP_FETCH_CONFIG_REQUESTED = 'APP_FETCH_CONFIG_REQUESTED';
export const APP_FETCH_CONFIG_STATUS = 'APP_FETCH_CONFIG_STATUS';

// TASK
export const TASK_FETCH_CONFIG_REQUESTED = 'TASK_FETCH_CONFIG_REQUESTED';
export const TASK_FETCH_CONFIG_STATUS = 'TASK_FETCH_CONFIG_STATUS';

export const TASK_FETCH_TASKS_REQUESTED = 'TASK_FETCH_TASKS_REQUESTED';
export const TASK_FETCH_TASKS_STATUS = 'TASK_FETCH_TASKS_STATUS';

// VISUAL
export const VISUAL_RESET = 'VISUAL_RESET';
export const VISUAL_SET_BACKGROUND_FILE = 'VISUAL_SET_BACKGROUND_FILE';
export const VISUAL_SET_TEXT = 'VISUAL_SET_TEXT';

// TTS
export const TTS_SAY_TEXT_REQUESTED = 'TTS_SAY_TEXT_REQUESTED';
export const TTS_SAY_TEXT_STATUS = 'TTS_SAY_TEXT_STATUS';

export const TTS_SET_RATE_REQUESTED = 'TTS_SET_RATE_REQUESTED';
export const TTS_SET_RATE_STATUS = 'TTS_SET_RATE_STATUS';

export const TTS_SET_PITCH_REQUESTED = 'TTS_SET_PITCH_REQUESTED';
export const TTS_SET_PITCH_STATUS = 'TTS_SET_PITCH_STATUS';

export const TTS_SET_LOCALE_REQUESTED = 'TTS_SET_LOCALE_REQUESTED';
export const TTS_SET_LOCALE_STATUS = 'TTS_SET_LOCALE_STATUS';

// CAMERA
export const CAMERA_TAKE_PICTURE_REQUESTED = 'CAMERA_TAKE_PICTURE_REQUESTED';
export const CAMERA_TAKE_PICTURE_STATUS = 'CAMERA_TAKE_PICTURE_STATUS';

export const CAMERA_OBJECT_DETECTED = 'CAMERA_OBJECT_DETECTED';
export const CAMERA_SET_TRACKING_OBJECT = 'CAMERA_SET_TRACKING_OBJECT';
